### ISSUE TITLE
 1주차 자바 기초 과제: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#1]
## 목표

자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기.

## 학습할 것

- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

## 마감기간

- 2021 4/1(목)

**Comment by JaeHee-K** [comment]
.

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-04-01-[java]-1-jvm

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/23

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/JVM%26JAVA.md
