### ISSUE TITLE
6. 자바 기초 과제: 패키지

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#11]
## 목표
자바의 패키지에 대해 학습하세요.

## 학습할 것 (필수)

- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- -classpath 옵션
- 접근지시자

## 마감일시
2021년 4월 29일 목요일 0시 5분

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/32

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-04-27-[java]-6.package/

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Package.md
