### ISSUE TITLE
7. 자바 기초 과제: 인터페이스

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#13]
## 목표
자바의 인터페이스에 대해 학습하세요.

## 학습할 것 (필수)

- 인터페이스 정의하는 방법
- 인터페이스 구현하는 방법
- 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
- 인터페이스 상속
- 인터페이스의 기본 메소드 (Default Method), 자바 8
- 인터페이스의 static 메소드, 자바 8
- 인터페이스의 private 메소드, 자바 9

## 마감일시
2021년 5월 3일 월요일 0시 5분

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/33

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-02-[java]-7-interface/

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Interface.md
