### ISSUE TITLE
8. 자바 기초 과제: 예외 처리

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#15]
## 목표
자바의 예외 처리에 대해 학습하세요.

## 학습할 것 (필수)

- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법

## 마감일시
2021년 5월 6일 목요일 5시

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/34

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Exception.md

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-06-[java]-8-exception/
