### ISSUE TITLE
9. 자바 기초 과제: 멀티쓰레드 프로그래밍

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#17]
## 목표
자바의 멀티쓰레드 프로그래밍에 대해 학습하세요.

## 학습할 것 (필수)

- Thread 클래스와 Runnable 인터페이스
- 쓰레드의 상태
- 쓰레드의 우선순위
- Main 쓰레드
- 동기화
- 데드락

## 마감일시
2021년 5월 10일 월요일 13시

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/MultiThread.md

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/35

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-10-[java]-9-thread/
