### ISSUE TITLE
10. 자바 기초 과제: Enum

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#19]
## 목표
자바의 열거형에 대해 학습하세요.

## 학습할 것 (필수)

- enum 정의하는 방법
- enum이 제공하는 메소드 (values()와 valueOf())
- java.lang.Enum
- EnumSet

## 마감일시
2021년 5월 14일 금요일 0시 5분까지.

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/36

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Enum.md

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-14-[java]-10-enum/
