### ISSUE TITLE
11. 자바 기초 과제: 애노테이션  

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#21]
## 목표
자바의 애노테이션에 대해 학습하세요.

## 학습할 것 (필수)
애노테이션 정의하는 방법
@retention
@target
@documented
애노테이션 프로세서

## 마감일시
2021년 5월 17일 월요일 0시 5분

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-16-[java]-11-annotation/

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Annotation.md

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/37
