### ISSUE TITLE
12. 자바 기초 과제: I/O

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#23]
## 목표
자바의 Input과 Ontput에 대해 학습하세요.

## 학습할 것 (필수)

- 스트림 (Stream) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O
- InputStream과 OutputStream
- Byte와 Character 스트림
- 표준 스트림 (System.in, System.out, System.err)
- 파일 읽고 쓰기

## 마감일시
2021년 5월 20일 목요일 13시

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/38

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-19-[java]-12-io/

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/IO.md
