### ISSUE TITLE
14. 자바 기초 과제: 람다식

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#27]
## 목표
자바의 람다식에 대해 학습하세요.

## 학습할 것 (필수)

- 람다식 사용법
- 함수형 인터페이스
- Variable Capture
- 메소드, 생성자 레퍼런스

## 마감일시
2021년 5월 27일 목요일 오후 1시까지

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/40

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Lambda.md

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-05-27-[java]-14-lambda/
