### ISSUE TITLE
2주차 자바 기초 과제: 자바 데이터 타입, 변수 그리고 배열

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#3]
## 목표
자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법을 익힙니다.

## 학습할 것

- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var

## 마감 일시 (한국 시간 기준)
2021년 4월 8일(목) 오후 1시

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/26

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-04-07-[java]-2-type,variable,array/

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Data-Type.md
