### ISSUE TITLE
5. 자바 기초 과제: 상속

### ISSUE THREAD

**Issue by changjunpyo** [cloud-platform-study/java-study#9]
## 목표
자바의 상속에 대해 학습하세요.

## 학습할 것 (필수)

- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
- 추상 클래스
- final 키워드
- Object 클래스

## 마감일시
2021년 4월 26일 월요일

**Comment by JaeHee-K** [comment]
https://xcv20123.tistory.com/31

**Comment by changjunpyo** [comment]
https://gogojun.com/java/2021-04-24-[java]-5-inheritance/

**Comment by kim-yisoo** [comment]
https://github.com/gashe-soo/java-study/blob/master/java-live-study/Inheritance.md
